package com.majesttyx.mcacapitals.capital;

public enum CapitalChronicleEventId {
    CAPITAL_MARRIAGE(CapitalChronicleEventType.ROYAL_MARRIAGE, "capital_marriage"),
    ROYAL_MARRIAGE(CapitalChronicleEventType.ROYAL_MARRIAGE, "royal_marriage"),
    LEGITIMIZED(CapitalChronicleEventType.LEGITIMIZED, "legitimized"),
    ROYAL_PARDON(CapitalChronicleEventType.NONE, "royal_pardon"),
    COURT_RECORD_REMOVED(CapitalChronicleEventType.NONE, "court_record_removed"),
    DISINHERITED(CapitalChronicleEventType.DISINHERITED, "disinherited"),
    EXECUTED_CONDEMNED(CapitalChronicleEventType.NONE, "executed_condemned"),
    EXECUTED_BY_CROWN(CapitalChronicleEventType.NONE, "executed_by_crown"),
    HEIR_APPARENT_NAMED(CapitalChronicleEventType.HEIR_APPARENT_NAMED, "heir_apparent_named"),
    OFFICE_RELIEVED(CapitalChronicleEventType.NONE, "office_relieved"),
    OFFICE_APPOINTED(CapitalChronicleEventType.NONE, "office_appointed"),
    GRAND_MAESTER_RELIEVED(CapitalChronicleEventType.NONE, "grand_maester_relieved"),
    GRAND_MAESTER_APPOINTED(CapitalChronicleEventType.GRAND_MAESTER_APPOINTED, "grand_maester_appointed"),
    COMMANDER_ARMY_RELIEVED(CapitalChronicleEventType.NONE, "commander_army_relieved"),
    COMMANDER_ARMY_APPOINTED(CapitalChronicleEventType.LORD_COMMANDER_APPOINTED, "commander_army_appointed"),
    DUCAL_ELEVATED(CapitalChronicleEventType.NEW_DUKE_OR_DUCHESS, "ducal_elevated"),
    ROYAL_GUARD_COMMANDER_APPOINTED(CapitalChronicleEventType.LORD_COMMANDER_APPOINTED, "royal_guard_commander_appointed"),
    ROYAL_GUARD_COMMANDER_VACANT(CapitalChronicleEventType.NONE, "royal_guard_commander_vacant"),
    ROYAL_GUARD_COMMANDER_RELIEVED(CapitalChronicleEventType.NONE, "royal_guard_commander_relieved"),
    SOVEREIGN_DIED_CONSORT_SURVIVES(CapitalChronicleEventType.SOVEREIGN_DEATH, "sovereign_died_consort_survives"),
    SOVEREIGN_DIED_NO_SUCCESSOR(CapitalChronicleEventType.SOVEREIGN_DEATH, "sovereign_died_no_successor"),
    SOVEREIGN_DIED_HEIR_INHERITED(CapitalChronicleEventType.PEACEFUL_TRANSFER, "sovereign_died_heir_inherited"),
    SOVEREIGN_DIED_SUCCESSOR_INHERITED(CapitalChronicleEventType.PEACEFUL_TRANSFER, "sovereign_died_successor_inherited"),
    ROYAL_GUARD_RELEASED_TRANSFER(CapitalChronicleEventType.NONE, "royal_guard_released_transfer"),
    ROYAL_GUARD_APPOINTED(CapitalChronicleEventType.ROYAL_GUARD_APPOINTED, "royal_guard_appointed"),
    ROYAL_GUARD_DISGRACED(CapitalChronicleEventType.NONE, "royal_guard_disgraced"),
    SOVEREIGN_DEATH_MOURNING(CapitalChronicleEventType.SOVEREIGN_DEATH, "sovereign_death_mourning"),
    ROYAL_FAMILY_MEMBER_DIED(CapitalChronicleEventType.SOVEREIGN_DEATH, "royal_family_member_died"),
    FRIEND_OF_CROWN_RECOGNIZED_PLAYER(CapitalChronicleEventType.NONE, "friend_of_crown_recognized_player"),
    CROWN_PEACE_RESTORED_PLAYER(CapitalChronicleEventType.NONE, "crown_peace_restored_player"),
    FRIEND_OF_CROWN_RECOGNIZED_COUNCIL(CapitalChronicleEventType.NONE, "friend_of_crown_recognized_council"),
    CROWN_PEACE_RESTORED_COUNCIL(CapitalChronicleEventType.NONE, "crown_peace_restored_council"),
    ENEMY_SENTENCE_COMPLETED(CapitalChronicleEventType.NONE, "enemy_sentence_completed"),
    CROWN_JUDGMENT(CapitalChronicleEventType.NONE, "crown_judgment"),
    ASYLUM_GRANTED_DESTINATION(CapitalChronicleEventType.NONE, "asylum_granted_destination"),
    ASYLUM_GRANTED_ORIGIN(CapitalChronicleEventType.NONE, "asylum_granted_origin"),
    ABDICATION_SUCCESSOR(CapitalChronicleEventType.ABDICATION, "abdication_successor"),
    AMBASSADOR_APPOINTED(CapitalChronicleEventType.NONE, "ambassador_appointed"),
    AMBASSADOR_RELIEVED(CapitalChronicleEventType.NONE, "ambassador_relieved"),
    PRISONER_DELIVERED(CapitalChronicleEventType.NONE, "prisoner_delivered"),
    WARRANT_EXECUTION_MARKED(CapitalChronicleEventType.NONE, "warrant_execution_marked"),
    WARRANT_EXECUTION_MARK_FAILED(CapitalChronicleEventType.NONE, "warrant_execution_mark_failed"),
    PRISONER_ESCAPED_EXILE(CapitalChronicleEventType.NONE, "prisoner_escaped_exile"),
    PRISONER_ESCAPED_EXILE_RECORD_FAILED(CapitalChronicleEventType.NONE, "prisoner_escaped_exile_record_failed"),
    SOVEREIGN_ACCLAIMED(CapitalChronicleEventType.CAPITAL_FOUNDED, "sovereign_acclaimed"),
    THRONE_CLAIMED(CapitalChronicleEventType.CAPITAL_FOUNDED, "throne_claimed"),
    HAND_APPOINTED(CapitalChronicleEventType.HAND_APPOINTED, "hand_appointed"),
    HAND_VACANT(CapitalChronicleEventType.NONE, "hand_vacant"),
    MASTER_OF_LAWS_APPOINTED(CapitalChronicleEventType.NONE, "master_of_laws_appointed"),
    MASTER_OF_LAWS_RELIEVED(CapitalChronicleEventType.NONE, "master_of_laws_relieved"),
    LORD_ELEVATED(CapitalChronicleEventType.NONE, "lord_elevated"),
    DUKE_ELEVATED(CapitalChronicleEventType.NEW_DUKE_OR_DUCHESS, "duke_elevated"),
    THRONE_SEIZED_VACANT_DEPOSITION(CapitalChronicleEventType.THRONE_SEIZED, "throne_seized_vacant_deposition"),
    THRONE_SEIZED_BY_FORCE(CapitalChronicleEventType.THRONE_SEIZED, "throne_seized_by_force"),
    PETITION_PEACEFUL_TRANSFER(CapitalChronicleEventType.PEACEFUL_TRANSFER, "petition_peaceful_transfer"),
    BETROTHAL_PLAYER_PETITION(CapitalChronicleEventType.NONE, "betrothal_player_petition"),
    BETROTHAL_ROYAL_RECOMMENDATION(CapitalChronicleEventType.NONE, "betrothal_royal_recommendation"),
    ACCUSATION_RENEWED(CapitalChronicleEventType.NONE, "accusation_renewed"),
    FALSE_ACCUSATION(CapitalChronicleEventType.NONE, "false_accusation"),
    FOUNDATION_DUKE_AND_SPOUSE(CapitalChronicleEventType.NEW_DUKE_OR_DUCHESS, "foundation_duke_and_spouse"),
    FOUNDATION_DUKE(CapitalChronicleEventType.NEW_DUKE_OR_DUCHESS, "foundation_duke"),
    SUCCESSION_DECREE_TRANSFER(CapitalChronicleEventType.PEACEFUL_TRANSFER, "succession_decree_transfer"),
    COURT_HERALD_APPOINTED(CapitalChronicleEventType.COURT_HERALD_APPOINTED, "court_herald_appointed"),
    MOURNING_DECLARED(CapitalChronicleEventType.SOVEREIGN_DEATH, "mourning_declared"),
    MOURNING_ENDED(CapitalChronicleEventType.MOURNING_ENDED, "mourning_ended"),
    ROYAL_CHILD_RECORDED(CapitalChronicleEventType.ROYAL_BIRTH, "royal_child_recorded"),
    CROWN_CHILD_RECORDED(CapitalChronicleEventType.CROWN_CHILD_BORN, "crown_child_recorded"),
    TRADE_AGREEMENT_CREATED(CapitalChronicleEventType.NONE, "trade_agreement_created"),
    TRADE_AGREEMENT_RENEWED(CapitalChronicleEventType.NONE, "trade_agreement_renewed"),
    TRADE_AGREEMENT_ENDED(CapitalChronicleEventType.NONE, "trade_agreement_ended"),
    TRADE_AGREEMENT_ENDED_REASON(CapitalChronicleEventType.NONE, "trade_agreement_ended_reason"),
    TRADE_AGREEMENT_ENDED_REQUESTED(CapitalChronicleEventType.NONE, "trade_agreement_ended_requested"),
    TRADE_AGREEMENT_ENDED_TERM_EXPIRED(CapitalChronicleEventType.NONE, "trade_agreement_ended_term_expired"),
    TRADE_AGREEMENT_ENDED_MILITARY_ATTACK(CapitalChronicleEventType.NONE, "trade_agreement_ended_military_attack"),
    TRADE_AGREEMENT_ENDED_WAR_DECLARED(CapitalChronicleEventType.NONE, "trade_agreement_ended_war_declared"),
    TRADE_AGREEMENT_ENDED_TRADE_IMPOSSIBLE(CapitalChronicleEventType.NONE, "trade_agreement_ended_trade_impossible"),
    TRADE_AGREEMENT_RENEWAL_PROPOSED(CapitalChronicleEventType.NONE, "trade_agreement_renewal_proposed"),
    BETROTHAL_AGREEMENT(CapitalChronicleEventType.NONE, "betrothal_agreement"),
    BETROTHAL_ESCORT_COMPLETED(CapitalChronicleEventType.NONE, "betrothal_escort_completed"),
    ROYAL_MARRIAGE_COMPLETED(CapitalChronicleEventType.ROYAL_MARRIAGE, "royal_marriage_completed"),
    WARDSHIP_AGREEMENT(CapitalChronicleEventType.NONE, "wardship_agreement"),
    WARDSHIP_ESCORT_COMPLETED(CapitalChronicleEventType.NONE, "wardship_escort_completed"),
    UNJUST_WAR(CapitalChronicleEventType.GENERIC_NOTABLE, "unjust_war"),
    TRUCE_BROKEN(CapitalChronicleEventType.GENERIC_NOTABLE, "truce_broken"),
    DIPLOMATIC_AGREEMENT_DISPATCHED(CapitalChronicleEventType.NONE, "diplomatic_agreement_dispatched"),
    DIPLOMATIC_AGREEMENT_ACCEPTED(CapitalChronicleEventType.NONE, "diplomatic_agreement_accepted"),
    DIPLOMATIC_AGREEMENT_REJECTED(CapitalChronicleEventType.NONE, "diplomatic_agreement_rejected"),
    DIPLOMATIC_PACKAGE_DISPATCHED(CapitalChronicleEventType.NONE, "diplomatic_package_dispatched"),
    DIPLOMATIC_PACKAGE_GRAVE_INSULT(CapitalChronicleEventType.NONE, "diplomatic_package_grave_insult"),
    DIPLOMATIC_PACKAGE_ACCEPTED_SOURCE(CapitalChronicleEventType.NONE, "diplomatic_package_accepted_source"),
    DIPLOMATIC_PACKAGE_ACCEPTED_TARGET(CapitalChronicleEventType.NONE, "diplomatic_package_accepted_target"),
    DIPLOMATIC_PACKAGE_RETURNED_SOURCE(CapitalChronicleEventType.NONE, "diplomatic_package_returned_source"),
    DIPLOMATIC_PACKAGE_RETURNED_TARGET(CapitalChronicleEventType.NONE, "diplomatic_package_returned_target"),
    DIPLOMATIC_PACKAGE_INSULT_RETURNED_SOURCE(CapitalChronicleEventType.NONE, "diplomatic_package_insult_returned_source"),
    DIPLOMATIC_PACKAGE_INSULT_RETURNED_TARGET(CapitalChronicleEventType.NONE, "diplomatic_package_insult_returned_target"),
    RELATIONS_WARNING_SENT(CapitalChronicleEventType.NONE, "relations_warning_sent"),
    DIPLOMATIC_AGREEMENT_PROPOSED(CapitalChronicleEventType.NONE, "diplomatic_agreement_proposed"),
    TRADE_CARAVAN_EXCHANGE(CapitalChronicleEventType.NONE, "trade_caravan_exchange"),
    WAR_BEGAN_ATTACK(CapitalChronicleEventType.GENERIC_NOTABLE, "war_began_attack"),
    WAR_BEGAN_ATTACK_TREATY_BROKEN(CapitalChronicleEventType.GENERIC_NOTABLE, "war_began_attack_treaty_broken"),
    WAR_DECLARED(CapitalChronicleEventType.GENERIC_NOTABLE, "war_declared"),
    TRUCE_ESTABLISHED(CapitalChronicleEventType.NONE, "truce_established"),
    TRUCE_EXPIRED(CapitalChronicleEventType.NONE, "truce_expired"),
    CAMPAIGN_PLANNED(CapitalChronicleEventType.GENERIC_NOTABLE, "campaign_planned"),
    CAMPAIGN_DEPLOYED(CapitalChronicleEventType.GENERIC_NOTABLE, "campaign_deployed"),
    FIELD_DEFENDERS_DEFEATED(CapitalChronicleEventType.GENERIC_NOTABLE, "field_defenders_defeated"),
    DEFENDING_SOVEREIGN_REFUSED_PEACE(CapitalChronicleEventType.GENERIC_NOTABLE, "defending_sovereign_refused_peace"),
    CAMPAIGN_DEFENDERS_SURRENDERED_NO_SOVEREIGN(CapitalChronicleEventType.GENERIC_NOTABLE, "campaign_defenders_surrendered_no_sovereign"),
    CAMPAIGN_DEFENDERS_SUED_FOR_PEACE(CapitalChronicleEventType.GENERIC_NOTABLE, "campaign_defenders_sued_for_peace"),
    CAMPAIGN_ENDED_RETURNED(CapitalChronicleEventType.GENERIC_NOTABLE, "campaign_ended_returned"),
    CAMPAIGN_ATTACKERS_DEFEATED(CapitalChronicleEventType.GENERIC_NOTABLE, "campaign_attackers_defeated"),
    CAMPAIGN_DEFENDERS_DEFEATED(CapitalChronicleEventType.GENERIC_NOTABLE, "campaign_defenders_defeated"),
    CAMPAIGN_SOVEREIGN_DEATH_RETREAT(CapitalChronicleEventType.SOVEREIGN_DEATH, "campaign_sovereign_death_retreat"),
    CAMPAIGN_PLANNED_ATTACK_INVALIDATED(CapitalChronicleEventType.NONE, "campaign_planned_attack_invalidated"),
    CAMPAIGN_CUSTOM_END(CapitalChronicleEventType.GENERIC_NOTABLE, "campaign_custom_end"),
    CAMPAIGN_PEACE_ACCEPTED(CapitalChronicleEventType.GENERIC_NOTABLE, "campaign_peace_accepted"),
    WAR_SETTLEMENT(CapitalChronicleEventType.GENERIC_NOTABLE, "war_settlement"),
    WAR_SETTLEMENT_NEGOTIATED(CapitalChronicleEventType.GENERIC_NOTABLE, "war_settlement_negotiated"),
    DEPOSITION_REMOVED_FROM_THRONE(CapitalChronicleEventType.THRONE_SEIZED, "deposition_removed_from_throne"),
    WARTIME_INTERREGNUM_BEGAN(CapitalChronicleEventType.SOVEREIGN_DEATH, "wartime_interregnum_began"),
    WARTIME_INTERREGNUM_ENDED_SOVEREIGN(CapitalChronicleEventType.PEACEFUL_TRANSFER, "wartime_interregnum_ended_sovereign"),
    WARTIME_INTERREGNUM_ENDED_RETURNED(CapitalChronicleEventType.PEACEFUL_TRANSFER, "wartime_interregnum_ended_returned"),
    WARTIME_HAND_APPOINTED(CapitalChronicleEventType.HAND_APPOINTED, "wartime_hand_appointed"),
    WARTIME_INTERREGNUM_NO_SUCCESSOR_CONSORT(CapitalChronicleEventType.SOVEREIGN_DEATH, "wartime_interregnum_no_successor_consort"),
    WARTIME_INTERREGNUM_NO_SUCCESSOR(CapitalChronicleEventType.SOVEREIGN_DEATH, "wartime_interregnum_no_successor"),
    WARTIME_INTERREGNUM_HEIR_INHERITED(CapitalChronicleEventType.PEACEFUL_TRANSFER, "wartime_interregnum_heir_inherited"),
    WARTIME_INTERREGNUM_SUCCESSOR_INHERITED(CapitalChronicleEventType.PEACEFUL_TRANSFER, "wartime_interregnum_successor_inherited"),
    ARREST_WARRANT_ISSUED(CapitalChronicleEventType.NONE, "arrest_warrant_issued"),
    ENEMY_DISCOVERED(CapitalChronicleEventType.NONE, "enemy_discovered"),
    NATURAL_DUKEDOM(CapitalChronicleEventType.NEW_DUKE_OR_DUCHESS, "natural_dukedom"),
    CAMPAIGN_RETREAT_ORDERED(CapitalChronicleEventType.GENERIC_NOTABLE, "campaign_retreat_ordered"),
    CHILD_SOVEREIGN_SUED_FOR_PEACE(CapitalChronicleEventType.GENERIC_NOTABLE, "child_sovereign_sued_for_peace"),
    CHILD_SOVEREIGN_REFUSED_PEACE(CapitalChronicleEventType.GENERIC_NOTABLE, "child_sovereign_refused_peace"),
    MONARCHY_REJECTED(CapitalChronicleEventType.NONE, "monarchy_rejected");

    private final CapitalChronicleEventType type;
    private final String path;

    CapitalChronicleEventId(CapitalChronicleEventType type, String path) {
        this.type = type;
        this.path = path;
    }

    public CapitalChronicleEventType type() {
        return type;
    }

    public String chronicleKey() {
        return "mcacapitals.chronicle.event." + path;
    }

    public String heraldKey() {
        return "mcacapitals.herald.event." + path;
    }

    public String path() {
        return path;
    }
}
