package com.example.mcacapitals.dialogue;

public enum CapitalDialogueKey {
    PETITION_SOVEREIGN_ONLY,
    PETITION_MISSING_VILLAGE,
    PETITION_AUDIENCE_REQUIRED,

    THRONE_NO_SOVEREIGN,
    THRONE_NOT_REIGNING,
    THRONE_PLAYER_HELD,
    THRONE_POPULATION_TOO_LOW,
    THRONE_LOW_STANDING,
    THRONE_ALREADY_RULES_OTHER,
    THRONE_SUCCESS,

    SEIZE_THRONE_NO_SOVEREIGN,
    SEIZE_THRONE_MISSING_VILLAGE,
    SEIZE_THRONE_NOT_IN_AUDIENCE,
    SEIZE_THRONE_LOW_REPUTATION,
    SEIZE_THRONE_NO_ADVANCEMENT,
    SEIZE_THRONE_NO_COMMANDER_SUPPORT,
    SEIZE_THRONE_SUCCESS,

    COMMANDER_POPULATION_TOO_LOW,
    COMMANDER_LOW_STANDING,
    COMMANDER_ALREADY_GRANTED,
    COMMANDER_ALREADY_HELD,
    COMMANDER_REASSIGN_FAILED,
    COMMANDER_SUCCESS,

    LORD_ALREADY_HIGHER,
    LORD_ALREADY_HELD,
    LORD_LOW_STANDING,
    LORD_NOT_ENOUGH_MASTERS,
    LORD_SUCCESS,

    DUKE_ALREADY_HELD,
    DUKE_POPULATION_TOO_LOW,
    DUKE_LOW_STANDING,
    DUKE_SUCCESS,

    BETROTHAL_NO_ELIGIBLE_MATCH,
    BETROTHAL_SELECTION_MISSING_VILLAGE,
    BETROTHAL_SELECTION_INVALID_TARGET,
    BETROTHAL_SELECTION_FAILED,
    BETROTHAL_SELECTION_SUCCESS,
    BETROTHAL_RECOMMEND_INVALID_TARGET,
    BETROTHAL_RECOMMEND_FAILED,
    BETROTHAL_RECOMMEND_SUCCESS,

    NEWS_MARRIAGE,
    NEWS_DEATH_OR_SUCCESSION,
    NEWS_MOURNING_DECLARED,
    NEWS_MOURNING_ENDED,
    NEWS_HEIR_NAMED,
    NEWS_DISINHERITED,
    NEWS_LEGITIMIZED,
    NEWS_THRONE_CHANGE,
    NEWS_CAPITAL_FOUNDED,
    NEWS_GENERIC_NOTABLE
}